// Code generated by Slice Machine. DO NOT EDIT.

import CardLinlks from './CardLinlks';
import MovieCards from './MovieCards';

export {
	CardLinlks,
	MovieCards,
};

export const components = {
	card_linlks: CardLinlks,
	movie_cards: MovieCards,
};
